plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'ir.buddy.xposedvoicechanger'
    compileSdk 35

    defaultConfig {
        applicationId "ir.buddy.xposedvoicechanger"
        minSdk 32
        targetSdk 35
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {

    implementation libs.appcompat
    implementation libs.material
    implementation libs.activity
    implementation libs.constraintlayout
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
    implementation 'com.github.dragoon000320:tarsosdsp:1.0'
    implementation 'de.robv.android.xposed:api:82'
}